#!/bin/sh

# TODO: Check for arguments

SHARE_MOUNT_PATH="$1"

echo "Mounting $SHARE_MOUNT_PATH share..."

# mount share with /etc/fstab entry
sleep 5
mount $SHARE_MOUNT_PATH

echo "Accessing mounted share..."

xdg-open $SHARE_MOUNT_PATH &

echo "Done."
