#!/bin/sh

cd $(dirname $0)

. "./__settings"

echo "Unmounting $SHARE_MOUNT_PATH share..."

umount $SHARE_MOUNT_PATH

echo "Mounting $SHARE_MOUNT_PATH share..."

# mount share with /etc/fstab entry
sleep 5
mount $SHARE_MOUNT_PATH

echo "Accessing mounted share..."

xdg-open $SHARE_MOUNT_PATH &

echo "Done."
