#!/bin/sh

# TODO: Check for arguments

VM_NAME=$1

VBoxManage snapshot $VM_NAME restorecurrent

if [ ! $? = 0 ]; then
    $message = "Error restoring the $VM_NAME VM snapshot!"
    echo $message
    notify-send -u critical $message
    exit 1
fi

VBoxManage startvm $VM_NAME --type headless

if [ ! $? = 0 ]; then
    $message = "Error starting the $VM_NAME VM!"
    echo $message
    notify-send -u critical $message
    exit 1
fi
