#!/bin/sh

cd $(dirname $0)

. "./__settings"

VBoxManage snapshot $VM_NAME restorecurrent

if [ ! $? = 0 ]; then
    $message = "Error restoring the $VM_NAME VM snapshot!"
    echo $message
    notify-send -u critical $message
    exit 1
fi

VBoxManage startvm $VM_NAME --type headless

if [ ! $? = 0 ]; then
    $message = "Error starting the $VM_NAME VM!"
    echo $message
    notify-send -u critical $message
    exit 1
fi

echo "Mounting $SHARE_MOUNT_PATH share..."

# TODO: Check for credentials file
sleep 5
mount $SHARE_MOUNT_PATH

echo "Accessing mounted share..."

xdg-open $SHARE_MOUNT_PATH &
