#!/bin/sh

# TODO: Check for arguments

VM_NAME=$1
VM_SNAPSHOT_PREFIX=$2

echo "Taking snapshot of VM state..."

VBoxManage snapshot $VM_NAME take "$VM_SNAPSHOT_PREFIX " --uniquename Number

if [ ! $? = 0 ]; then
    $message = "Error taking the $VM_NAME VM snapshot!"
    echo $message
    notify-send -u critical $message
    exit 1
fi

VBoxManage controlvm $VM_NAME poweroff

if [ ! $? = 0 ]; then
    $message = "Error stopping the $VM_NAME VM!"
    echo $message
    notify-send -u critical $message
    exit 1
fi
